name: action-review

on:
  push:
    branches:
      - code-review
  pull_request:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
              ~/.gradle/caches/modules-*
              ~/.gradle/caches/jars-*
              ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Archieve APK
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: build-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  android-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build APK
        run: ./gradlew lintDebug

      - name: Archieve Report
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.xml

  integration:
    if: success()
    needs: [build-apk, android-lint]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          path: artifact

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}



