name: my-automation

on:
  push:
    branches:
      - action-firebase-testlab
  pull_request:
    branches:
      - action-firebase-testlab

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Test APK
        run: ./gradlew assembleDebugAndroidTest

      - name: Print Directory List
        run: ls -R app/build/outputs